#pragma once

#define IDC_VIEWERPE_FILE_COMBO 1001

#define IDR_VIEWERPE_MENU 2001

#define IDM_VIEWERPE_FILE_EXPORT_TEXT 40001
#define IDM_VIEWERPE_FILE_EXPORT_MARKDOWN 40002
#define IDM_VIEWERPE_FILE_REFRESH 40003
#define IDM_VIEWERPE_OTHER_NEXT 40004
#define IDM_VIEWERPE_OTHER_PREVIOUS 40005
#define IDM_VIEWERPE_OTHER_FIRST 40006
#define IDM_VIEWERPE_OTHER_LAST 40007
#define IDM_VIEWERPE_FILE_EXIT 40008

#define IDM_VIEWERPE_VIEW_GOTO_TOP 40201
#define IDM_VIEWERPE_VIEW_GOTO_BOTTOM 40202

#define IDS_VIEWERPE_NAME 100
#define IDS_VIEWERPE_DESCRIPTION 101
#define IDS_VIEWERPE_STATUS_LOADING 102
#define IDS_VIEWERPE_ERROR_NO_FILEIO 103
#define IDS_VIEWERPE_ERROR_OPEN_FAILED 104
#define IDS_VIEWERPE_ERROR_TOO_LARGE 105
#define IDS_VIEWERPE_ERROR_READ_FAILED 106
#define IDS_VIEWERPE_ERROR_PARSE_FAILED 107
#define IDS_VIEWERPE_EXPORT_DIALOG_TITLE 108
#define IDS_VIEWERPE_EXPORT_FILTER_TEXT 109
#define IDS_VIEWERPE_EXPORT_FILTER_MARKDOWN 110
#define IDS_VIEWERPE_EXPORT_ERROR_NO_REPORT 111
#define IDS_VIEWERPE_EXPORT_ERROR_FAILED 112
