Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
. (Join-Path $repoRoot 'Tools\TestRunPlan.ps1')
$generator = Join-Path $repoRoot 'Tools\TerminalEngine\Generate-TerminalEngineFixtures.ps1'
$corpus = Join-Path $repoRoot 'Specs\Terminal\TerminalEngineFixtureCorpus.v1.json'
$header = Join-Path $repoRoot 'Tools\TerminalEngine\Generated\TerminalEngineFixtures.v1.h'

Describe 'TerminalEngine frozen fixture generator' {
    It 'reproduces the checked 29-fixture header and nonzero manifest exactly' {
        $result = & $generator -Corpus $corpus -Header $header -Verify
        $result.verified | Should Be $true
        $result.fixtureCount | Should Be 29
        $result.fixtureManifestSha256 | Should Match '^[1-9a-f][0-9a-f]{63}$'
        $result.headerSha256 | Should Match '^[0-9a-f]{64}$'
    }

    It 'fails closed when one generated byte changes' {
        $scratch = New-RSTestSandboxScratchDirectory `
            -RepoRoot $repoRoot `
            -Harness 'terminal-engine-fixture-generator-pester' `
            -Case ([guid]::NewGuid().ToString('N'))
        $copy = Join-Path $scratch 'TerminalEngineFixtures.v1.h'
        Copy-Item -LiteralPath $header -Destination $copy
        [IO.File]::AppendAllText($copy, "`n", [Text.UTF8Encoding]::new($false))
        $failedClosed = $false
        try {
            & $generator -Corpus $corpus -Header $copy -Verify | Out-Null
        }
        catch {
            $failedClosed = $true
        }
        $failedClosed | Should Be $true
    }

    It 'freezes isolated action plans and the exact 8MiB performance payload' {
        $text = [IO.File]::ReadAllText(
            $header,
            [Text.UTF8Encoding]::new($false, $true))
        $text | Should Match 'kPerformancePayload\{kPerformanceFixtureIds, 8388608ULL, "[0-9a-f]{64}"\}'
        $text | Should Match '"probe-terminal-text-ledger"'
        $text | Should Match '"snapshot-copy-fail-retry"'
        $text | Should Match '"snapshot-static-kitty"'
        $text | Should Match '"kitty-direct-png"'
        $text | Should Match 'k_kitty_direct_png_input'
        $text | Should Match 'ff0000ff'
        $text | Should Match '"admit-external-events"'
        $text | Should Match 'InputStep\{InputOp::RepeatByte, "", 10, 67108865ULL\}'
    }
}
