<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <RSParentDirectoryBuildProps>$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\'))</RSParentDirectoryBuildProps>
  </PropertyGroup>
  <Import Project="$(RSParentDirectoryBuildProps)" Condition="'$(RSParentDirectoryBuildProps)'!=''" />

  <PropertyGroup Condition="'$(RSIsFirstPartyProject)'=='true' and '$(MSBuildProjectExtension)'=='.vcxproj'">
    <RSPluginSharedDefaultsEnabled Condition="'$(RSPluginSharedDefaultsEnabled)'==''">true</RSPluginSharedDefaultsEnabled>
  </PropertyGroup>

  <ItemDefinitionGroup Condition="'$(RSPluginSharedDefaultsEnabled)'=='true'">
    <ClCompile>
      <DisableSpecificWarnings>4710;4711;%(DisableSpecificWarnings)</DisableSpecificWarnings>
      <ExternalIncludePath>$(VcpkgInstalledDir)$(RSVcpkgTriplet)\include;$(ExternalIncludePath)</ExternalIncludePath>
      <ExternalWarningLevel>TurnOffAllWarnings</ExternalWarningLevel>
      <AdditionalOptions>/utf-8 /external:anglebrackets /external:templates- /wd5045 /wd4820 %(AdditionalOptions)</AdditionalOptions>
      <AdditionalIncludeDirectories>$(SolutionDir)Common;$(SolutionDir)RedSalamander;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <SubSystem>Windows</SubSystem>
      <GenerateDebugInformation>true</GenerateDebugInformation>
    </Link>
  </ItemDefinitionGroup>
</Project>
