#pragma once

// Shared numeric contract for the host-owned FolderView context menu cloned by
// ViewerSpace. Keep these definitions resource-compiler compatible.
#define IDR_FOLDERVIEW_ITEM_CONTEXT 138

#define IDM_FOLDERVIEW_CONTEXT_OPEN 33280
#define IDM_FOLDERVIEW_CONTEXT_OPEN_WITH 33281
#define IDM_FOLDERVIEW_CONTEXT_DELETE 33282
#define IDM_FOLDERVIEW_CONTEXT_RENAME 33283
#define IDM_FOLDERVIEW_CONTEXT_COPY 33284
#define IDM_FOLDERVIEW_CONTEXT_PASTE 33285
#define IDM_FOLDERVIEW_CONTEXT_PROPERTIES 33286
#define IDM_FOLDERVIEW_CONTEXT_MOVE 33287
#define IDM_FOLDERVIEW_CONTEXT_VIEW_SPACE 33288
#define IDM_FOLDERVIEW_CONTEXT_SELECT_ALL 33289
#define IDM_FOLDERVIEW_CONTEXT_UNSELECT_ALL 33290
#define IDM_FOLDERVIEW_CONTEXT_ARTIFACT_INSPECT 33291
#define IDM_FOLDERVIEW_CONTEXT_ARTIFACT_REVEAL 33292
#define IDM_FOLDERVIEW_CONTEXT_CUT 33295
#define IDM_FOLDERVIEW_CONTEXT_REFRESH 33296
