#pragma once

#define IDS_VIEWERVLC_NAME 100
#define IDS_VIEWERVLC_DESCRIPTION 101
#define IDS_VIEWERVLC_WINDOW_CAPTION 102
#define IDS_VIEWERVLC_BUTTON_PLAY 103
#define IDS_VIEWERVLC_BUTTON_PAUSE 104
#define IDS_VIEWERVLC_BUTTON_STOP 105
#define IDS_VIEWERVLC_BUTTON_SNAPSHOT_ELLIPSIS 106
#define IDS_VIEWERVLC_LABEL_TIME_UNKNOWN 107
#define IDS_VIEWERVLC_MISSING_TITLE 108
#define IDS_VIEWERVLC_MISSING_BODY 109
#define IDS_VIEWERVLC_MISSING_LINK 110
#define IDS_VIEWERVLC_FILEDLG_FILTER_PNG 111
#define IDS_VIEWERVLC_FILEDLG_TITLE_SNAPSHOT 112
#define IDS_VIEWERVLC_MISSING_LINK_LABEL 113
