#pragma once

// IDS_FILESYSTEMMTP_NAME and IDS_FILESYSTEMMTP_FSNAME are loaded through
// LoadEmbeddedStringResource because they are language-neutral identity tokens.
#define IDS_FILESYSTEMMTP_NAME 50001
#define IDS_FILESYSTEMMTP_DESCRIPTION 50002
#define IDS_FILESYSTEMMTP_FSNAME 50003
#define IDS_FILESYSTEMMTP_MENU_NO_DEVICES 50004
#define IDS_FILESYSTEMMTP_MENU_PROPERTIES 50005
#define IDS_FILESYSTEMMTP_MENU_DISCONNECT 50006
